### ISSUE TITLE
[Feature request] Allow whitelisting IPs

### ISSUE THREAD

**Issue by DrummerSi** [MichaelBelgium/adonisjs-maintenance#1]
Having a secret key to bypass the maintenance mode is fine.

But I think it'd also be really good to allow passing in one or more IP addresses that are allowed to access the system.

This would help in some test situations where you need an external service to still be able to call your website, but can't modify the request to add query strings or headers.

**Comment by DrummerSi** [comment]
Oh, I see you already allow IPs to be whitelisted.. it's just not documented

**Comment by MichaelBelgium** [comment]
Yeah, there is a property `allowedIps` in `maintenance.json` that only gets pushed to when you enter the secret key (so you don't have to add the secret key on every request), so it's like an indirect feature already

But it's a good idea as there could be an option to the maintenance command to manually push ips already to that array. which makes it a whitelist array
